import type { Artist } from "./Type/PersonType";

export const initialArtists: Artist[] = [
    {
        id: 'a1',
        firstName: 'Leonardo',
        lastName: 'da Vinci',
        born: 1452,
        died: 1519,
        nationality: 'Italian',
    },
    {
        id: 'a2',
        firstName: 'Rembrandt',
        lastName: 'van Rijn',
        born: 1606,
        died: 1669,
        nationality: 'Dutch',
    },
    {
        id: 'a3',
        firstName: 'Katsushika',
        lastName: 'Hokusai',
        born: 1760,
        died: 1849,
        nationality: 'Japanese',
    },
    {
        id: 'a4',
        firstName: 'Frida',
        lastName: 'Kahlo',
        born: 1907,
        died: 1954,
        nationality: 'Mexican',
    },
    {
        id: 'a5',
        firstName: 'Pablo',
        lastName: 'Picasso',
        born: 1881,
        died: 1973,
        nationality: 'Spanish',
    },
    {
        id: 'a6',
        firstName: 'Utagawa',
        lastName: 'Hiroshige',
        born: 1797,
        died: 1858,
        nationality: 'Japanese',
    },
    {
        id: 'a7',
        firstName: 'Gerard',
        lastName: 'Sekoto',
        born: 1913,
        died: 1993,
        nationality: 'South African',
    },
    {
        id: 'a8',
        firstName: 'Tarsila',
        lastName: 'do Amaral',
        born: 1886,
        died: 1973,
        nationality: 'Brazilian',
    },
    {
        id: 'a9',
        firstName: 'Michelangelo',
        lastName: 'Buonarroti',
        born: 1475,
        died: 1564,
        nationality: 'Italian',
    },
    {
        id: 'a10',
        firstName: 'Wassily',
        lastName: 'Kandinsky',
        born: 1866,
        died: 1944,
        nationality: 'Russian',
    },
    {
        id: 'a11',
        firstName: 'Qi',
        lastName: 'Baishi',
        born: 1864,
        died: 1957,
        nationality: 'Chinese',
    },
    {
        id: 'a12',
        firstName: 'Wifredo',
        lastName: 'Lam',
        born: 1902,
        died: 1982,
        nationality: 'Cuban',
    },
    {
        id: 'a13',
        firstName: 'El',
        lastName: 'Anatsui',
        born: 1944,
        died: undefined,
        nationality: 'Ghanaian',
    },
    {
        id: 'a14',
        firstName: 'Diego',
        lastName: 'Rivera',
        born: 1886,
        died: 1957,
        nationality: 'Mexican',
    },
    {
        id: 'a15',
        firstName: 'Artemisia',
        lastName: 'Gentileschi',
        born: 1593,
        died: 1656,
        nationality: 'Italian',
    },
    {
        id: 'a16',
        firstName: 'Yayoi',
        lastName: 'Kusama',
        born: 1929,
        died: undefined,
        nationality: 'Japanese',
    },
    {
        id: 'a17',
        firstName: 'William',
        lastName: 'Kentridge',
        born: 1955,
        died: undefined,
        nationality: 'South African',
    },
    {
        id: 'a18',
        firstName: 'Francisco',
        lastName: 'Goya',
        born: 1746,
        died: 1828,
        nationality: 'Spanish',
    },
    {
        id: 'a19',
        firstName: 'Xu',
        lastName: 'Bing',
        born: 1955,
        died: undefined,
        nationality: 'Chinese',
    },
    {
        id: 'a20',
        firstName: 'Oswaldo',
        lastName: 'Guayasamín',
        born: 1919,
        died: 1999,
        nationality: 'Ecuadorian',
    },
    {
        id: 'a21',
        firstName: 'Vincent',
        lastName: 'van Gogh',
        born: 1853,
        died: 1890,
        nationality: 'Dutch',
    },
    {
        id: 'a22',
        firstName: 'Chéri',
        lastName: 'Samba',
        born: 1956,
        died: undefined,
        nationality: 'Congolese',
    },
    {
        id: 'a23',
        firstName: 'Albrecht',
        lastName: 'Dürer',
        born: 1471,
        died: 1528,
        nationality: 'German',
    },
    {
        id: 'a24',
        firstName: 'Amrita',
        lastName: 'Sher-Gil',
        born: 1913,
        died: 1941,
        nationality: 'Indian',
    },
    {
        id: 'a25',
        firstName: 'Georgia',
        lastName: "O'Keeffe",
        born: 1887,
        died: 1986,
        nationality: 'American',
    },
];